seed=42
log_dir="logs"
model_dir="."
checkpoints_dir="chkpt"
results_dir="results"
lr=0.001
batch_size=5
valid_batch_size=5
max_num_epochs=200
energy_weight=1.0
forces_weight=0
stress_weight=0
E0s='average'
loss='universal'
enable_cueq=true
compute_stress=false
compute_forces=false
#stress_key='REF_stress'
energy_key='log_klat'
#forces_key='REF_forces'
eval_interval=1 
error_table='PerAtomMAE'
model="MACE"
interaction_first="RealAgnosticDensityInteractionBlock"
interaction="RealAgnosticDensityResidualInteractionBlock"
num_interactions=2
correlation=3
max_ell=3
r_max=5.0 
max_L=2
num_channels=128
num_radial_basis=8
MLP_irreps="16x0e"
scaling='rms_forces_scaling'
weight_decay=1e-8
ema=true #maybe true
ema_decay=0.995
scheduler_patience=5
pair_repulsion=false
distance_transform="Agnesi"
patience=40
amsgrad=true
device='cuda'
clip_grad=100
keep_checkpoints=true
save_all_checkpoints=true
restart_latest=true
default_dtype="float64"
num_workers=4
save_cpu=true
wandb=true
wandb_project="auto-kappa"
wandb_entity="mhp27"
wandb_name="auto-kappa"


